### ISSUE TITLE
Documentación / Ejemplos

### ISSUE THREAD

**Issue by Javierkaiser** [emilioastarita/facturajs#1]
Buenas
¿sería posible expandir un poco más la documentación? O tal vez más ejemplos de uso.

Saludos

**Comment by emilioastarita** [comment]
¿que necesitas hacer? El ejemplo no te anduvo ?

**Comment by Javierkaiser** [comment]
Todavía no llegué a la parte de usar en sí la conexión con la AFIP.
El ejemplo que hay creo entenderlo bien, pero me quedan algunas dudas del uso, tipo el de conseguir la numeración de la factura, como sería con diferentes tipos de facturas (A, B, C, etc).
Por ahí se podría mejorar el ejemplo comentando cuales campos son obligatorios, cuales opcionales, como sería con varios productos / servicios.

**Comment by emilioastarita** [comment]
La verdad es que yo tengo un uso muy específico y no probé esos casos de uso. Si alguno que lo este usando se copa a comentar lo agregamos a la doc.

**Comment by emilioastarita** [comment]
Bueno nadie contesto, cierro.
