### ISSUE TITLE
la AFIP usa TLS de 1974

### ISSUE THREAD

**Issue by tulsidas** [emilioastarita/facturajs#12]
Buenas, arranqué con esto para hacer unas pruebas y resulta que nuestra amada AFIP usa TLS del año del choto con tamaño de claves de 4 bits, entonces falla con:

`(node:14790) UnhandledPromiseRejectionWarning: Error: write EPROTO 139949712528768:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2156`

Busqué y se puede obligar a openssl a aceptar cifrados arcaicos, inseguros y pedorros (porque imaginate pedirle a la AFIP que actualicen sus servicios, ¡ja!), entonces lo corro así:
`node --tls-cipher-list="TLS_RSA_WITH_AES_256_GCM_SHA384" dist/examples/last-bill.js`

y falla con:

`(node:14406) UnhandledPromiseRejectionWarning: Error [ERR_SOCKET_CLOSED]: Socket is closed`

Y hasta ahí llegué... ¿ideas?

**Comment by tulsidas** [comment]
Bueno, resulta que comentando la línea 
`CipherString = DEFAULT@SECLEVEL=2` de `/etc/ssl/openssl.cnf` todo se resuelve, básicamente le estás diciendo a OpenSSL que baje el nivel de seguridad (porque AFIP)

**Comment by emilioastarita** [comment]
Con que versión de node te pasó esto? Estoy de vacas pero reabro asi lo agregamos a la doc y no se la choca el siguiente

**Comment by tulsidas** [comment]
tengo `node v12.21.0`, pero estoy casi seguro que el tema no es node, sino el sistema operativo ya que node delega en openssl la funcionalidad de encriptar/firmar/etc.

tengo `OpenSSL 1.1.1j  16 Feb 2021`

y como te decía en mi mensaje anterior, Debian en `/etc/ssl/openssl.conf` tiene ese flag donde no permite certificados con firmas débiles (como la afip jeje)

**Comment by mbenedettini** [comment]
Documentaron esto al final? Me acaba de pasar esto al cambiar de imagen base, puedo mandar un PR rapido

**Comment by tulsidas** [comment]
Update porque OpenSSL se pone más estricto y AFIP sigue usando cosas muy viejas:

Descubrí que la lista de ciphers de AFIP contiene ciphers decentes, sólo que no en el orden correcto. También que se puede pilotear de forma muy fácil sin tocar nada de código ni la configuración de OpenSSL, pasando un parametro al ejecutar node:

`node --tls-cipher-list='ECDHE-RSA-AES128-GCM-SHA256' <resto de los argumentos>`

data que puede sumar:

listar qué ciphers soporta tu entorno:

`node -p crypto.constants.defaultCoreCipherList | tr ':' '\n'`

listar qué ciphers soporta el server de AFIP:

`nmap -sV --script ssl-enum-ciphers -p 443 servicios1.afip.gov.ar`

espero sirva, salute

**Comment by zapi2003** [comment]
Me tiraba este error:
FaultString: HTTP Could not connect to host

Es porque la AFIP usa el TLS 1.0 

Modifique el wsfev1.class.php y anda perfecto:

	$opts = ['ssl' => 
                [
                'ciphers' => 'DEFAULT@SECLEVEL=1',
                'verify_peer' => false,
                'verify_peer_name' => false
                ]
            ];

    $this->client = new SoapClient($this->path.self::WSDL, array( 
				'soap_version' => SOAP_1_2,
				'location'     => self::WSFEURL,
				'exceptions'   => 0,
				'trace'        => 1,
				'stream_context' => stream_context_create($opts)
				)
    ); 

Espero que les sirva. Gracias!!!!
