### ISSUE TITLE
Cannot find type definition file for 'bluebird'

### ISSUE THREAD

**Issue by specie** [emilioastarita/facturajs#2]
al correr tsc, me dá el error: 

node_modules/facturajs/dist/AfipServices.d.ts(1,23): error TS2688: Cannot find type definition file for 'bluebird'.
node_modules/facturajs/dist/AfipServices.d.ts(3,26): error TS7016: Could not find a declaration file for module 'bluebird'. '/fe_AFIP_test/node_modules/bluebird/js/release/bluebird.js' implicitly has an 'any' type.
  Try `npm install @types/bluebird` if it exists or add a new declaration (.d.ts) file containing `declare module 'bluebird';`

**Comment by emilioastarita** [comment]
Te paso como buildeo yo, si te anda lo subimos al README, sino avisame y le buscamos la vuelta:
```bash
git clone git@github.com:emilioastarita/facturajs.git
cd facturajs
yarn
yarn build
```
En `dist/` deberías tener el paquete generado.

Ojo que para usar el paquete no necesitas las fuentes y podes consumirlo a traves de npm/yarn en tu app.

Saludos!

**Comment by emilioastarita** [comment]
A partir de un PR de @mbenedettini eliminamos bluebird. Así que cierro. Cualquier cosa avisen.
