### ISSUE TITLE
Forma de pago? Items?

### ISSUE THREAD

**Issue by tercerapersona** [emilioastarita/facturajs#21]
Hola, por lo que veia en el ejemplo del repo para generar un comprobante, no es necesario especificar forma de pago, ni los items que componen la factura.

<img width="794" alt="Screenshot 2023-08-01 at 10 28 53" src="https://github.com/emilioastarita/facturajs/assets/16053355/77c3f1b5-40c4-405f-86e4-bcfbd8e34b24">

Esto es requerido en la [web oficial](https://auth.afip.gov.ar/contribuyente_/login.xhtml?action=SYSTEM&system=rcel), pero no parece fallar sin mandarlos por API. No hay problema en no mandarlos?
En caso de querer agregarlo tampoco encontré en la [documentación](https://www.afip.gob.ar/fe/ayuda/documentos/Manual-desarrollador-V.2.21.pdf) como hacerlo

<img width="487" alt="Screenshot 2023-08-01 at 10 28 28" src="https://github.com/emilioastarita/facturajs/assets/16053355/5c4b43c6-4996-4e47-9a8a-c67239fdb5ca">

**Comment by emilioastarita** [comment]
La verdad no sé yo vengo creandolos así sin problema
