### ISSUE TITLE
Facturas A 

### ISSUE THREAD

**Issue by federicobaiocco** [emilioastarita/facturajs#7]
Hola, facturajs permite generar comprobantes tipo 1, es decir A? Porque no encuentro la forma de pasar los datos que necesito mandar para generar comprobantes tipo A, por ejemplo Ivas y tributos.

**Comment by emilioastarita** [comment]
Sí, debería servir. Tenes que pasar 1 en vez de 11. Y para el resto de los parametros buscá:
https://www.afip.gob.ar/facturadecreditoelectronica/documentos/manual_desarrollador_COMPG.pdf

Ahi adentro busca `FECAESolicitar` que es el método que termina llamando el `createBill` de facturajs.

Ahi tenes un ejemplo de Factura A y como mapean los params al webservice.

**Comment by federicobaiocco** [comment]
Muchas gracias Emilio!
